### ISSUE TITLE
1.11.2-1.3.0 Ticking Entity

### ISSUE THREAD

**Issue by MisterShawn** [KidsDontPlay/Harvesting-Animals#3]
https://gist.github.com/sdaddy/8b54e586391496ae96fa590a45adb020

**Comment by MisterShawn** [comment]
Updated, but now it added canSustainPlant.

https://gist.github.com/sdaddy/1555c3f291abce374f548d9c7d901e89

**Comment by KidsDontPlay** [comment]
I can't reproduce the crash (and the previous one too).
what animals try to eat what food?

**Comment by MisterShawn** [comment]
I believe the crashes started after I added the [RealWorld](http://10paksmods.net) mod. The animals may be from the Animania mod, but I tested them before adding RW and they behaved correctly. Both crashes were from new worlds during generation. RW adds small patches of crops to world gen, so newly spawned animals may be trying to eat the crops RW adds. I'll test later this evening after work.

**Comment by MisterShawn** [comment]
I grew some celery from RealWorld, a cow from Animania ate it, and the game crashed like previously. I'm 100% sure it's because of the RealWorld crop as I tested CEA with Animania cows and chickens with vanilla crops and it worked wonderfully.

**Comment by KidsDontPlay** [comment]
the author of realworld should fix it
